# Generated by Django 4.2.30 on 2026-04-18 07:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_update_plans_v2'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('meeting_request', 'Meeting Request'), ('personal_info_request', 'Personal Info Request'), ('social_media_solicitation', 'Social Media Solicitation'), ('photo_video_request', 'Photo/Video Request'), ('grooming_language', 'Grooming Language'), ('secrecy_request', 'Secrecy Request'), ('threats_bullying', 'Threats / Bullying'), ('gift_bribery', 'Gift / Bribery'), ('other', 'Other')], default='other', max_length=50)),
                ('category_label', models.CharField(blank=True, max_length=200)),
                ('sms_message', models.TextField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='CommunityPeakTimeStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour_start', models.PositiveIntegerField(unique=True)),
                ('count', models.PositiveIntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['hour_start'],
            },
        ),
        migrations.CreateModel(
            name='CommunityThreatStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('meeting_request', 'Meeting Request'), ('personal_info_request', 'Personal Info Request'), ('social_media_solicitation', 'Social Media Solicitation'), ('photo_video_request', 'Photo/Video Request'), ('grooming_language', 'Grooming Language'), ('secrecy_request', 'Secrecy Request'), ('threats_bullying', 'Threats / Bullying'), ('gift_bribery', 'Gift / Bribery'), ('other', 'Other')], max_length=50, unique=True)),
                ('count', models.PositiveIntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-count'],
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('device_type', models.CharField(choices=[('pc', 'PC'), ('console', 'Console'), ('mobile', 'Mobile'), ('other', 'Other')], default='pc', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('child', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='core.child')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='core.userprofile')),
            ],
        ),
        migrations.RemoveField(
            model_name='plan',
            name='max_children',
        ),
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_name', models.CharField(max_length=200)),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='core.child')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='core.device')),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_name', models.CharField(max_length=200)),
                ('speaker', models.CharField(blank=True, max_length=200)),
                ('content', models.TextField()),
                ('message_type', models.CharField(choices=[('voice', 'Voice'), ('text', 'Text')], default='text', max_length=20)),
                ('is_flagged', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('alert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='core.alertevent')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='core.device')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddField(
            model_name='alertevent',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='core.child'),
        ),
    ]
