# Generated by Django 6.0.5 on 2026-05-23 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_schema_redesign'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='raw_context',
            field=models.TextField(blank=True, help_text='Flagged conversation snippet from on-device LLM'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='summary',
            field=models.TextField(help_text='LLM-generated summary of what happened'),
        ),
    ]
